### ISSUE TITLE
Allow name copied from iconify website to be used 

### ISSUE THREAD

**Issue by cderv** [mcanouil/quarto-iconify#19]
This would improve user experience 

Here is what I did 

- Go to https://icon-sets.iconify.design/ to look for icon
- Find one I want. Example: https://icon-sets.iconify.design/noto/package/
- Click the copy button
	![image](https://github.com/mcanouil/quarto-iconify/assets/6791940/ae755e9f-7f8c-4dbb-9630-22b69749970f)

This will get `noto:package`, but currently the shortcode is expecting `noto package`

It seems the whole website support this pattern. 

Maybe this would be possible to support this by detecting the `:` and splitting it into `set` and `icon` ? 

You know better - just throwing the idea.

**Comment by mcanouil** [comment]
Done!
Thanks for the idea.
